# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        args: ['--write']
        additional_dependencies:
          - prettier@2.0.5
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.0.0-rc.0
    hooks:
      - id: eslint
        additional_dependencies:
          [
            '@typescript-eslint/eslint-plugin@2.31.0',
            '@typescript-eslint/parser@2.31.0',
            'eslint@6.8.0',
            'eslint-config-airbnb@18.1.0',
            'eslint-config-prettier@6.11.0',
            'eslint-import-resolver-typescript@2.0.0',
            'eslint-plugin-import@2.20.2',
            'eslint-plugin-json@2.1.1',
            'eslint-plugin-jsx-a11y@6.2.3',
            'eslint-plugin-prettier@3.1.3',
            'eslint-plugin-react@7.19.0',
            'eslint-plugin-react-hooks@4.0.0',
            'typescript@3.8.3',
          ]
